global:
  imageRegistry: ghcr.io/arshitchoubey18/aiops-self-healing-kubernetes-platform
  imageTag: 2761391cfa5df89879a40f6a4289dae4651b748b
  imagePullPolicy: IfNotPresent
namespace:
  create: false
  name: aiops
secrets:
  existingSecret: aiops-secrets
aiAgent:
  enabled: true
  replicas: 1
  image:
    repository: ai-agent
  service:
    port: 8080
  env:
    OLLAMA_BASE_URL: http://ollama:11434
    OLLAMA_MODEL: qwen2.5:0.5b-instruct-q4_0
    OLLAMA_TIMEOUT_SECONDS: "600"
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
healerController:
  enabled: true
  replicas: 1
  image:
    repository: healer-controller
  env:
    POLL_INTERVAL_SECONDS: "30"
    AI_AGENT_URL: http://aio-self-healing-ai-agent:8080
    HEALING_MODE: dry-run
    CRASHLOOP_ACTION: rollback
    WATCH_NAMESPACES: default,demo
    GITHUB_REPOSITORY: arshitchoubey18/AIOps-Self-Healing-Kubernetes-Platform
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
discordBot:
  enabled: false
  replicas: 1
  image:
    repository: discord-bot
  env:
    AI_AGENT_URL: http://aio-self-healing-ai-agent:8080
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
ollama:
  enabled: true
  image: ollama/ollama:0.5.4
  model: qwen2.5:0.5b-instruct-q4_0
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
    limits:
      cpu: "1"
      memory: 3Gi
